#!/usr/bin/env pwsh
# scripts/list-tools.ps1 — validate tools/* and regenerate TOOLS.md (Windows-native twin).
# Usage: pwsh scripts/list-tools.ps1 [-Check]
[CmdletBinding()]
param(
  [switch]$Check,
  [switch]$Help
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

if ($Help) {
  [Console]::Error.WriteLine('Usage: pwsh scripts/list-tools.ps1 [-Check]')
  exit 2
}

$root = Get-RepoRoot
$toolsDir = Join-Path $root 'tools'
$index = Join-Path $root 'TOOLS.md'
$requiredKeys = @('name', 'description', 'category', 'owner', 'status', 'compat', 'impact', 'last_verified')
$validStatus = @('incubating', 'stable', 'deprecated')
$validImpact = @('read-only', 'local', 'system')
$nbhy = [string][char]0x2011
$utf8 = New-Object System.Text.UTF8Encoding($false)

$fail = 0
$count = 0
$rows = New-Object System.Collections.Generic.List[string]

$dirs = @()
if (Test-Path -LiteralPath $toolsDir) {
  $dirs = Get-ChildItem -Directory -LiteralPath $toolsDir
}
foreach ($d in $dirs) {
  $slug = $d.Name
  if ($slug -eq '_archived' -or $slug -eq 'archived') { continue }
  $count++
  $meta = Join-Path $d.FullName 'metadata.yaml'
  $readme = Join-Path $d.FullName 'README.md'
  if (-not (Test-Path -LiteralPath $meta)) { Write-Err "${slug}: missing metadata.yaml"; $fail = 1; continue }
  if (-not (Test-Path -LiteralPath $readme)) { Write-Err "${slug}: missing README.md"; $fail = 1; continue }
  # Exactly one entrypoint; its native test is required and examples/ is optional.
  $entries = @()
  foreach ($m in @('main.sh', 'main.py', 'main.ps1', 'main.rb')) {
    if (Test-Path -LiteralPath (Join-Path $d.FullName $m)) { $entries += $m }
  }
  if ($entries.Count -eq 0) {
    Write-Err "${slug}: no entrypoint (main.sh|main.py|main.ps1|main.rb)"; $fail = 1
  }
  elseif ($entries.Count -gt 1) {
    Write-Err "${slug}: multiple entrypoints (keep exactly one main.*)"; $fail = 1
  }
  else {
    $ext = [IO.Path]::GetExtension($entries[0]).TrimStart('.')
    if (-not (Test-Path -LiteralPath (Join-Path $d.FullName "tests/test_basic.$ext"))) {
      Write-Err "${slug}: missing tests/test_basic.$ext (native test for $($entries[0]))"; $fail = 1
    }
    $examples = Join-Path $d.FullName 'examples'
    if ((Test-Path -LiteralPath $examples) -and -not (Test-Path -LiteralPath (Join-Path $examples "basic.$ext"))) {
      Write-Err "${slug}: examples/ must contain basic.$ext"; $fail = 1
    }
  }
  foreach ($k in $requiredKeys) {
    $pattern = '^' + [regex]::Escape($k) + ':'
    if (-not (Select-String -LiteralPath $meta -Pattern $pattern -Quiet)) {
      Write-Err "${slug}: metadata.yaml missing key: $k"; $fail = 1
    }
  }
  $name = Get-MetaValue -Path $meta -Key 'name'
  $desc = Get-MetaValue -Path $meta -Key 'description'
  $cat = Get-MetaValue -Path $meta -Key 'category'
  $status = Get-MetaValue -Path $meta -Key 'status'
  $owner = Get-MetaValue -Path $meta -Key 'owner'
  if ($name -ne $slug) { Write-Err "${slug}: name '$name' != dir"; $fail = 1 }
  if ($validStatus -notcontains $status) { Write-Err "${slug}: bad status '$status'"; $fail = 1 }
  $impact = Get-MetaValue -Path $meta -Key 'impact'
  if ($validImpact -notcontains $impact) {
    Write-Err "${slug}: bad impact '$impact' (read-only|local|system)"; $fail = 1
  }
  $slugDisp = $slug.Replace('-', $nbhy)
  $catDisp = $cat.Replace('-', $nbhy)
  $rows.Add("| ``$slugDisp`` | $desc | $catDisp | $status | $owner |")
}

if ($Check) {
  if ($fail -ne 0) { Die 'list-tools -Check FAILED' }
  Write-Info "list-tools -Check OK ($count tools)"
  exit 0
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# TOOLS.md')
$lines.Add('')
$lines.Add('> Generated by `scripts/list-tools.sh` or `scripts/list-tools.ps1`. Do not edit by hand.')
$lines.Add('')
if ($count -eq 0) {
  $lines.Add('_No tools published yet. Propose the first one in Issues with the `proposal` label._')
} else {
  $lines.Add('| Tool | Description | Category | Status | Owner |')
  $lines.Add('|---|---|---|---|---|')
  foreach ($r in $rows) { $lines.Add($r) }
}
[System.IO.File]::WriteAllText($index, (($lines -join "`n") + "`n"), $utf8)
Write-Info "regenerated TOOLS.md ($count tools)"
