#!/usr/bin/env bash
# scripts/list-tools.sh — validate tools/* and regenerate TOOLS.md.
# Usage: bash scripts/list-tools.sh [--check]
set -euo pipefail
IFS=$' \t\n'
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=common.sh
source "$HERE/common.sh"

MODE="write"
if [ "${1:-}" = "--check" ]; then MODE="check"; fi
if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  echo "Usage: bash scripts/list-tools.sh [--check]" >&2
  exit 2
fi

need_cmd awk grep sed
ROOT="$(repo_root)"
TOOLS_DIR="$ROOT/tools"
INDEX="$ROOT/TOOLS.md"
NBHY="$(printf '\342\200\221')" # U+2011 non-breaking hyphen: keeps table cells from splitting

yget() {
  awk -F': ' -v k="$2" '$1==k{sub(/^[^:]+: */,""); gsub(/["'\'']/,""); print; exit}' "$1" 2> /dev/null
}

fail=0
rows=""
count=0
for d in "$TOOLS_DIR"/*/; do
  [ -d "$d" ] || continue
  slug="$(basename "$d")"
  case "$slug" in "*"*)
    log_warn "no tools found"
    break
    ;;
  esac
  case "$slug" in "_archived" | "archived") continue ;; esac
  count=$((count + 1))
  meta="$d/metadata.yaml"
  readme="$d/README.md"
  [ -f "$meta" ] || {
    log_error "$slug: missing metadata.yaml"
    fail=1
    continue
  }
  [ -f "$readme" ] || {
    log_error "$slug: missing README.md"
    fail=1
    continue
  }
  # Exactly one entrypoint; its native test is required and examples/ is optional.
  entry=""
  entries=0
  for m in sh py ps1 rb; do
    if [ -x "$d/main.$m" ]; then
      entry="$m"
      entries=$((entries + 1))
    fi
  done
  case "$entries" in
    0)
      log_error "$slug: no executable entrypoint (main.sh|main.py|main.ps1|main.rb)"
      fail=1
      ;;
    1)
      [ -f "$d/tests/test_basic.$entry" ] || {
        log_error "$slug: missing tests/test_basic.$entry (native test for main.$entry)"
        fail=1
      }
      if [ -d "$d/examples" ] && [ ! -f "$d/examples/basic.$entry" ]; then
        log_error "$slug: examples/ must contain basic.$entry"
        fail=1
      fi
      ;;
    *)
      log_error "$slug: multiple entrypoints (keep exactly one main.*)"
      fail=1
      ;;
  esac
  for k in name description category owner status compat impact last_verified; do
    grep -q "^$k:" "$meta" || {
      log_error "$slug: metadata.yaml missing key: $k"
      fail=1
    }
  done
  name="$(yget "$meta" name)"
  desc="$(yget "$meta" description)"
  cat_="$(yget "$meta" category)"
  status="$(yget "$meta" status)"
  owner="$(yget "$meta" owner)"
  [ "$name" = "$slug" ] || {
    log_error "$slug: name '$name' != dir"
    fail=1
  }
  case "$status" in incubating | stable | deprecated) ;; *)
    log_error "$slug: bad status '$status'"
    fail=1
    ;;
  esac
  impact="$(yget "$meta" impact)"
  case "$impact" in read-only | local | system) ;; *)
    log_error "$slug: bad impact '$impact' (read-only|local|system)"
    fail=1
    ;;
  esac
  slug_disp="${slug//-/$NBHY}"
  cat_disp="${cat_//-/$NBHY}"
  rows="$rows| \`$slug_disp\` | $desc | $cat_disp | $status | $owner |
"
done

if [ "$MODE" = "check" ]; then
  if [ "$fail" -ne 0 ]; then die "list-tools --check FAILED"; fi
  log_info "list-tools --check OK ($count tools)"
  exit 0
fi

{
  echo "# TOOLS.md"
  echo ""
  echo "> Generated by \`scripts/list-tools.sh\` or \`scripts/list-tools.ps1\`. Do not edit by hand."
  echo ""
  if [ "$count" -eq 0 ]; then
    echo "_No tools published yet. Propose the first one in Issues with the \`proposal\` label._"
  else
    echo "| Tool | Description | Category | Status | Owner |"
    echo "|---|---|---|---|---|"
    printf '%s' "$rows"
  fi
} > "$INDEX"
log_info "regenerated TOOLS.md ($count tools)"
